//
//  PhotoSceneInteractor.swift
//  Photolyze
//
//  Created by Mac on 05.09.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoSceneBusinessLogic {
    func storePhoto(request: PhotoScene.StorePhoto.Request)
    func savePhoto(request: PhotoScene.SavePhoto.Request)
}

protocol PhotoSceneDataStore {
    var currentFilteredPhoto: CIImage? { get set }
}

class PhotoSceneInteractor: PhotoSceneDataStore {
    
    var presenter: PhotoScenePresentationLogic?
    var worker: PhotoSceneWorker?
    
    private let context = CIContext()
    
    //MARK: DataStore
    var currentFilteredPhoto: CIImage?
    
    // MARK: Do local stuff
    
}

extension PhotoSceneInteractor: PhotoSceneBusinessLogic {
    
    func storePhoto(request: PhotoScene.StorePhoto.Request) {
        self.currentFilteredPhoto = request.image
        
        let response = PhotoScene.StorePhoto.Response()
        self.presenter?.presentStorePhoto(response: response)
    }
    
    func savePhoto(request: PhotoScene.SavePhoto.Request) {
        var message: String? {
            didSet {
                let response = PhotoScene.SavePhoto.Response(message: message)
                self.presenter?.presentSavePhoto(response: response)
            }
        }
        
        if let ciImage = self.currentFilteredPhoto,
           let cgImage = self.context.createCGImage(ciImage, from: ciImage.extent) {
                let filteredImage = UIImage(cgImage: cgImage, scale: 1.0, orientation: .right)
                self.worker?.save(maybeImage: filteredImage) { msg in
                    message = msg
                }
        } else {
            message = "No image to save in album"
        }


    }
    

}
